In [1]:
import torch
import numpy as np

### Tensor -- basic data structure

Tensors are similar to numpy’s arrays, except that tensors can run on GPUs or other hardware accelerators. 

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [11]:
x_data.add_(1)

tensor([[2, 3],
        [4, 5]])

In [12]:
x_data = x_data.add(1)

tensor([[2, 3],
        [4, 5]])

In [16]:
x_data.shape

torch.Size([2, 2])

In [13]:
np_array = np.array([0, 1])
x_np = torch.from_numpy(np_array)

In [14]:
x_np

tensor([0, 1])

In [17]:
x_ones = torch.ones_like(x_data)

In [19]:
x_zeros = torch.zeros_like(x_data)

In [22]:
x_randoms = torch.rand_like(x_data, dtype=torch.float)

In [25]:
x_randoms.shape
x_randoms.dtype
x_randoms.device

device(type='cpu')

### Tensor indexing

In [26]:
x_data

tensor([[2, 3],
        [4, 5]])

In [29]:
x_data[:, 0]

tensor([2, 4])

In [28]:
x_data[1, :]

tensor([4, 5])

### Tensor operation

In [30]:
x_data.T

tensor([[2, 4],
        [3, 5]])

In [33]:
x_data

tensor([[2, 3],
        [4, 5]])

In [31]:
torch.matmul(x_data, x_data.T)

tensor([[13, 23],
        [23, 41]])

In [32]:
torch.mul(x_data, x_data.T)

tensor([[ 4, 12],
        [12, 25]])

In [34]:
x_data.grad

In [35]:
x_data.requires_grad

False