In [1]:
import torch
import numpy as np

### Tensor -- basic data structure

Tensors are similar to numpy’s arrays, except that tensors can run on GPUs or other hardware accelerators. 

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_array = np.array([0, 1])
x_np = torch.from_numpy(np_array)

In [5]:
x_np

tensor([0, 1])

In [9]:
x_ones = torch.ones_like(x_data) 
x_zeros = torch.zeros_like(x_data)
x_randoms = torch.rand_like(x_data, dtype=torch.float)

In [10]:
x_ones

tensor([[1, 1],
        [1, 1]])

In [11]:
x_zeros

tensor([[0, 0],
        [0, 0]])

In [12]:
x_randoms

tensor([[0.2342, 0.4331],
        [0.9410, 0.6869]])

In [13]:
print(f"Shape of tensor: {x_randoms.shape}")
print(f"Datatype of tensor: {x_randoms.dtype}")
print(f"Device tensor is stored on: {x_randoms.device}")

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Tensor indexing

In [14]:
x_data

tensor([[1, 2],
        [3, 4]])

In [17]:
x_data[:, 1]

tensor([2, 4])

In [18]:
x_data[1, :]

tensor([3, 4])

### Tensor operation

In [19]:
x_data

tensor([[1, 2],
        [3, 4]])

In [21]:
x_data.T # transpose

tensor([[1, 3],
        [2, 4]])

In [24]:
torch.matmul(x_data, x_data.T) # matrix multiplication

tensor([[ 5, 11],
        [11, 25]])

In [25]:
torch.mul(x_data, x_data.T)

tensor([[ 1,  6],
        [ 6, 16]])

In [29]:
x_data.add_(1)
x_data

tensor([[2, 3],
        [4, 5]])

In [31]:
x_data.grad ## returns the gradient of a tensor in models